import type { SourceDefinition } from "./types";

export const SOURCE_REGISTRY = {
  "aeroe-kommune": {
    id: "aeroe-kommune",
    name: "Ærø Kommune — mødeplaner",
    url: "https://www.aeroekommune.dk/politik-og-indflydelse/moedeplaner",
    organizerId: "aeroe-kommune",
    categoryIds: ["politik-kommune"],
  },
  "aeroe-kirkeliv": {
    id: "aeroe-kirkeliv",
    name: "Ærø Kirkeliv — kalender",
    url: "https://widget.churchdesk.com/da/w/1709/event/7HsDjgjjLaLL/1/1350954",
    organizerId: "aeroe-kirkeliv",
    categoryIds: ["kirke"],
  },
  "aeroe-bibliotek": {
    id: "aeroe-bibliotek",
    name: "Ærø Folkebibliotek — arrangementer",
    url: "https://www.arrebib.dk/arrangementer",
    organizerId: "aeroe-folkebibliotek",
    categoryIds: ["musik-kultur"],
  },
  facebook: {
    id: "facebook",
    name: "Facebook — offentlig opdagelse",
    url: "https://www.facebook.com/events/",
    organizerId: "aeroe-kalenderen",
    categoryIds: ["andet"],
  },
  "rise-sif": {
    id: "rise-sif",
    name: "Rise Skytte- & Idrætsforening — aktiviteter",
    url: "https://www.conventus.dk/publicBooking/public/getResources?organization=206",
    organizerId: "rise-sif",
    categoryIds: ["sport-motion"],
  },
  "dn-aeroe": {
    id: "dn-aeroe",
    name: "Danmarks Naturfredningsforening — Ærø",
    url: "https://arrangementer.dn.dk/",
    organizerId: "dn-aeroe",
    categoryIds: ["natur"],
  },
  "ritual-momoyoga": {
    id: "ritual-momoyoga",
    name: "Ritual — gruppehold hos Momoyoga",
    url: "https://www.momoyoga.com/nurtureaeroe/schedule",
    organizerId: "ritual-aeroe",
    categoryIds: ["sport-motion"],
  },
  "aeroe-kommune-events": {
    id: "aeroe-kommune-events",
    name: "Ærø Kommune — Det sker",
    url: "https://www.aeroekommune.dk/om-kommunen/kommunikation-og-presse/det-sker",
    organizerId: "aeroe-kommune",
    categoryIds: ["politik-kommune"],
  },
  "aeldresagen-aeroe": {
    id: "aeldresagen-aeroe",
    name: "Ældre Sagen Ærø — aktiviteter og kurser",
    url: "https://www.aeldresagen.dk/lokalafdelinger/aeroe/aktiviteter-og-kurser?sortering=dato",
    organizerId: "aeldresagen-aeroe",
    categoryIds: ["forening-faellesskab"],
  },
  "aeroe-folkedans": {
    id: "aeroe-folkedans",
    name: "Ærø Folkedanserforening — kommende begivenheder",
    url: "https://6165826142842.site123.me/",
    organizerId: "aeroe-folkedans",
    categoryIds: ["sport-motion", "forening-faellesskab"],
  },
  viften: {
    id: "viften",
    name: "Viften — ture og begivenheder",
    url: "https://www.viften.net/ture",
    organizerId: "viften",
    categoryIds: ["boern-familie"],
  },
  "aeroe-folkeuniversitet": {
    id: "aeroe-folkeuniversitet",
    name: "Ærø Folkeuniversitet — foredrag",
    url: "https://fuko.dk/komite/aeroe-folkeuniversitet/",
    organizerId: "aeroe-folkeuniversitet",
    categoryIds: ["musik-kultur"],
  },
  motorfabrikken: {
    id: "motorfabrikken",
    name: "Motorfabrikken Marstal — kulturkalender",
    url: "https://www.motorfabrikkenmarstal.com/kultur",
    organizerId: "motorfabrikken",
    categoryIds: ["musik-kultur"],
  },
  "ommel-bk": {
    id: "ommel-bk",
    name: "Ommel BK — hjemmekampe hos DBU Fyn",
    url: "https://www.dbufyn.dk/resultater/klub/1464/kampprogram",
    organizerId: "ommel-bk",
    categoryIds: ["sport-motion"],
  },
  marnav: {
    id: "marnav",
    name: "Marstal Navigationsskole — offentlige arrangementer",
    url: "https://marnav.nemtilmeld.dk/",
    organizerId: "marnav",
    categoryIds: ["andet"],
  },
  "campus-aeroe": {
    id: "campus-aeroe",
    name: "Campus Ærø — offentlige arrangementer",
    url: "https://campusaeroe.dk/events/",
    organizerId: "campus-aeroe",
    categoryIds: ["andet"],
  },
  "ommel-samvirke": {
    id: "ommel-samvirke",
    name: "Ommel Samvirke — aktivitetskalender",
    url: "https://www.ommelsamvirke.dk/aktivitetskalender",
    organizerId: "ommel-samvirke",
    categoryIds: ["forening-faellesskab"],
  },
  "kunsthoejskolen-aeroe": {
    id: "kunsthoejskolen-aeroe",
    name: "Kunsthøjskolen på Ærø — korte kurser",
    url: "https://www.kunstaeroe.dk/for-og-efter%C3%A5rskurser",
    organizerId: "kunsthoejskolen-aeroe",
    categoryIds: ["musik-kultur"],
  },
  "soeby-lokalraad": {
    id: "soeby-lokalraad",
    name: "Søby Lokalråd — arrangementer",
    url: "https://soebylokalraad.dk/11/en/node/12",
    organizerId: "soeby-lokalraad",
    categoryIds: ["forening-faellesskab"],
  },
  "aeroe-hotel-events": {
    id: "aeroe-hotel-events",
    name: "Ærø Hotel — arrangementer",
    url: "https://www.aeroehotel.dk/event-list",
    organizerId: "aeroe-hotel",
    categoryIds: ["musik-kultur"],
  },
  "aeroeskoebing-grand-prix": {
    id: "aeroeskoebing-grand-prix",
    name: "Ærøskøbing Grand Prix",
    url: "https://www.xn--rgrandprix-c6a1t.dk/",
    organizerId: "aeroeskoebing-grand-prix",
    categoryIds: ["boern-familie", "sport-motion"],
  },
  "aeroe-klatreklub": {
    id: "aeroe-klatreklub",
    name: "Ærø Klatreklub — faste aktiviteter",
    url: "https://aekk.klub-modul.dk/default.aspx",
    organizerId: "aeroe-klatreklub",
    categoryIds: ["sport-motion"],
  },
  "aeroe-tennisklub": {
    id: "aeroe-tennisklub",
    name: "Ærø Tennisklub — faste aktiviteter",
    url: "https://aeroetennisklub.dk/faste-aktiviteter/",
    organizerId: "aeroe-tennisklub",
    categoryIds: ["sport-motion"],
  },
  "parkinsonforeningen-aeroe": {
    id: "parkinsonforeningen-aeroe",
    name: "Parkinsonforeningen — Klub Ærø",
    url: "https://parkinson.dk/kredse/2823-fyn/klubber/",
    organizerId: "parkinsonforeningen-aeroe",
    categoryIds: ["forening-faellesskab"],
  },
  "aeroe-rideklub": {
    id: "aeroe-rideklub",
    name: "Ærø Rideklub — aktivitetskalender",
    url: "https://www.aeroerideklub.dk/events-1",
    organizerId: "aeroe-rideklub",
    categoryIds: ["sport-motion", "forening-faellesskab"],
  },
  "aeroe-golfklub": {
    id: "aeroe-golfklub",
    name: "Ærø Golf Klub — turneringskalender",
    url: "https://www.aeroegolf.dk/turneringer.aspx",
    organizerId: "aeroe-golfklub",
    categoryIds: ["sport-motion"],
  },
  "marstal-if": {
    id: "marstal-if",
    name: "Marstal IF — kommende hjemmekampe",
    url: "https://www.marstalif.dk/fodbold/kommende-kampe/",
    organizerId: "marstal-if",
    categoryIds: ["sport-motion"],
  },
  "marstal-billard-klub": {
    id: "marstal-billard-klub",
    name: "Marstal Billard Klub — kommende hjemmekampe",
    url: "https://spiller.ddbu-admin.dk/?m=1005&klubnr=511",
    organizerId: "marstal-billard-klub",
    categoryIds: ["sport-motion", "forening-faellesskab"],
  },
  "aeroeskoebing-sejlklub": {
    id: "aeroeskoebing-sejlklub",
    name: "Ærøskøbing Sejlklub — aktivitetskalender",
    url: "https://calendar.google.com/calendar/ical/9db3eee6cb77ad0a86cb2c024117df053701c9e5e4898f548914f560650e3df9%40group.calendar.google.com/public/basic.ics",
    organizerId: "aeroeskoebing-sejlklub",
    categoryIds: ["sport-motion", "forening-faellesskab"],
  },
  "aeroe-bridgeklub": {
    id: "aeroe-bridgeklub",
    name: "Ærø Bridgeklub — turneringsoversigt",
    url: "https://www.bridge.dk/4596/Turneringsoversigt.html",
    organizerId: "aeroe-bridgeklub",
    categoryIds: ["forening-faellesskab"],
  },
  ahop: {
    id: "ahop",
    name: "Aktivitetshuset OvenPaa — faste aktiviteter",
    url: "https://ahop.dk/",
    organizerId: "ahop",
    categoryIds: ["forening-faellesskab"],
  },
  "aeroe-svoemmeklub": {
    id: "aeroe-svoemmeklub",
    name: "Ærø Svømmeklub — holdprogram",
    url: "https://aero.klub-modul.dk/cms/TeamOverviewProgramList.aspx",
    organizerId: "aeroe-svoemmeklub",
    categoryIds: ["sport-motion", "boern-familie"],
  },
  "marstal-marineforening": {
    id: "marstal-marineforening",
    name: "Marstal Marineforening — aktiviteter",
    url: "https://www.marstalmarineforening.dk/aktiviteter/",
    organizerId: "marstal-marineforening",
    categoryIds: ["forening-faellesskab"],
  },
} as const satisfies Record<string, SourceDefinition>;

export type RegisteredSourceId = keyof typeof SOURCE_REGISTRY;
